### GET all posts
GET {{host}}/posts

### GET all posts from a user
GET {{host}}/posts/1

### POST add a new post
POST {{host}}/posts
Content-Type: application/json

{
  "id_user": 1,
  "image": null,
  "message": "Rebonjour les emmerdeurs",
  "parent_post": null
}

### PUT update a post
PUT {{host}}/posts/1
Content-Type: application/json

{
  "image": null,
  "message": "J'ai modifié le message encore une fois :p"
}

### DELETE a POST
DELETE {{host}}/posts/4