### Inits
@defaultDomain = http://localhost:3000

### getAllByPost(idPost)
GET {{defaultDomain}}/reports/1
 
### getOne(idPost, idUser)
GET {{defaultDomain}}/reports/1/1

### addOne()
POST {{defaultDomain}}/reports
Content-Type: application/json

{
    "idPost":1,
    "idUser":1,
    "message":"message"
}