
### login() as admin
# @name admin
POST {{host}}/users/login
Content-Type: application/json

{
    "email":"test3.test@student.vinci.be",
    "password":"test"
}

> {% client.global.set("adminToken", response.body.token);%}

### login() as user
# @name user
POST {{host}}/users/login
Content-Type: application/json

{
    "email":"test6.test@student.vinci.be",
    "password":"test"
}

> {% client.global.set("userToken", response.body.token);%}


### register() as user
# @name user
POST {{host}}/users/register
Content-Type: application/json

{
  "forename":"test",
  "lastname":"test",
  "email":"test6.test@student.vinci.be",
  "username":"test6",
  "password":"test"
}

> {% client.global.set("userToken", response.body.token);%}


### getProfileInformationsByEmail(email)
GET {{host}}/users/profile/francois.bardijn@vinci.be
Authorization: {{userToken}}

### getAllActiveUsers()
GET {{host}}/users
Authorization: {{adminToken}}

### disconnect()
GET {{host}}/users/disconnect


### delete()
DELETE {{host}}/users/90