

### login() as admin
# @name admin
POST {{host}}/users/login
Content-Type: application/json

{
    "email":"francois.bardijn@student.vinci.be",
    "password":"admin"
}

> {% client.global.set("adminToken", response.body.token);%}

### login() as user
# @name user
POST {{host}}/users/login
Content-Type: application/json

{
    "email":"guillaume.feron@student.vinci.be",
    "password":"user"
}

> {% client.global.set("userToken", response.body.token);%}

### getAll()
GET {{host}}/users
Authorization: {{adminToken}}


### getUserById()
GET {{host}}/users/2
Authorization: {{userToken}}


### updateUser()
PUT {{host}}/users/1
Content-Type: application/json
Authorization: {{userToken}}

{
    "forename":"Test",
    "lastname":"Test",
    "email":"Test.Test@student.vinci.be",
    "password":"Test"
}

### login()
POST {{host}}/users/login
Content-Type: application/json

{
    "email":"a.feon@student.vini.be",
    "password":"jesuisguigui"
}


### register()
POST {{host}}/users/register
Content-Type: application/json

{
    "forename":"Victor",
    "lastname":"Rijks",
    "email":"victor.rijks@vinci.be",
    "password":"mdp"
}

### login()
POST {{host}}/users/login
Content-Type: application/json

{
    "email":"alex.ottoy@vinci.be",
    "password":"mdp"
}

### disconnect()
GET {{host}}/users/disconnect


### delete()
DELETE {{host}}/users/5